config/routes.rb
Hopjoy::Application.routes.draw do
  root :to => "home#index"
  get "/about" => "home#about"
  get "/projects/:slug" => "projects#show"
  get "/projects/:slug/:page" => "projects#lesson"

  resources :environments
  resources :languages do
    get ":environment", :action => "environment", :on => :member, :as => "environment"
  end
  
end

app/models/environment.rb
class Environment < ActiveRecord::Base
  include MarkdownFileHelper
  markdownify :filename => "slug", :path => "pages/environments/:name/:section.md"
  
  has_many :projects
  has_many :environments_languages
  has_many :languages, :through => :environments_languages
  

  def name
    self.slug.to_s.gsub("-", " ").gsub(/\w+/) { |s| s.capitalize }
  end
  
end

app/models/environments_language.rb
class EnvironmentsLanguage < ActiveRecord::Base
  belongs_to :environment
  belongs_to :language
end

app/models/intro.rb
require 'rdiscount'
class Intro
  include MarkdownFileHelper
  markdownify :filename => :slug, :path => "pages/:name-:section.md"
  
  attr_accessor :slug

  
  def languages
    []
  end
  
  def initialize(path)
    self.slug = path
  end  
  
  def name
    self.slug.to_s.gsub("-", " ").capitalize
  end
    
  
  
end

app/models/language.rb
class Language < ActiveRecord::Base
  include MarkdownFileHelper
  markdownify :filename => "slug", :path => "pages/languages/:name/:section.md"
  
  has_many :languages_projects
  has_many :projects, :through => :languages_projects

  has_many :environments_languages
  has_many :environments, :through => :environments_languages

  def name
    self.slug.to_s.gsub("-", " ").gsub(/\w+/) { |s| s.capitalize }
  end
  
end

app/models/languages_project.rb
class LanguagesProject < ActiveRecord::Base
  belongs_to :project
  belongs_to :language
end

app/models/markdown_file_helper.rb
module MarkdownFileHelper

  def self.included(model)
    model.extend(ClassMethods)
    class << model; attr_accessor :markdown_path, :markdown_filename end
  end

  def content(section=nil)
    read section
  end
    
  def read(section)
    if self.content_exists?(section)
      RDiscount.new(File.new(path_to_markdown(section)).read).to_html
    else
      ""
    end
  end
  
  def content_exists?(section)
    File.exists? path_to_markdown(section)
  end
  
  def path_to_markdown(section)
    self.class.markdown_path.gsub(":name", self.send(self.class.markdown_filename).to_s).gsub(":section", section.to_s)
  end

  module ClassMethods
    
    def markdownify(opts={})
      opts[:filename] ||= "name"
      opts[:path] ||= ""

      self.markdown_path = opts[:path].to_s
      self.markdown_filename = opts[:filename].to_s
    end
    
  end # ClassMethods
  
end # MarkdownFileHelper

app/models/page.rb
require 'rdiscount'
class Page

  include MarkdownFileHelper
  markdownify :filename => "name", :path => "pages/:name.md"


  def self.get(path)
    if File.exists?("pages/#{path}.md")
      puts "eh!"
      RDiscount.new(File.new("pages/#{path}.md").read).to_html
    else
      ""
    end
  end  

end

app/models/project.rb
class Project < ActiveRecord::Base
  include MarkdownFileHelper
  markdownify :filename => "slug", :path => "pages/projects/:name.md"
  
  has_many :languages_projects
  has_many :languages, :through => :languages_projects
  belongs_to :environment
  
  def name
    self.slug.to_s.gsub("-", " ").gsub(/\w+/) { |s| s.capitalize }
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :pages_tags
  has_many :pages, :through => :pages_tags

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController

  def index
    @intro = Environment.new(:slug => "web-application-environment")
    @environments = Environment.all
  end
  
  def show
    @environment = Environment.find_by_slug!(params[:id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index 
    @environments = Environment.all
    @languages = Language.all
    
    @intro = Page.get("intro")
  end
  
  def about
  
  end
      
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def show    
    @language = Language.find_by_slug!(params[:id])
  end
  
  def environment
    @language = Language.find_by_slug!(params[:id])
    @environment = @language.environments.find_by_slug!(params[:environment])
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def show
    @project = Project.find_by_slug!(params[:slug])
    @environment = @project.environment
  end

  def lesson
    @project = Project.find_by_slug!(params[:slug])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/environments/index.html.erb
<div class="row" >
	<h2 class="main-block highlight"><%= @intro.name %></h2>
</div>

<%= render :partial => "partials/intro", :object => @intro %>

<p>
	Next you should learn about specific types of application environments,
	especially those you want to make applications for.
	<br/>Environments are listed below:
</p>

<ul class="media-grid">
<% @environments.each do |env| %>
  <li>
    <a href="<%= environment_path(env.slug) %>" style="text-align:center">
      <%= env.name %>
      <img class="thumbnail" src="http://placehold.it/90x90" alt="">
    </a>
  </li>
<% end %>
</ul>

app/views/environments/show.html.erb
<div id="<%= @environment.slug %>" class="row">
  <h2 class="main-block highlight">
    <%= @environment.name %>
  </h2>
</div>

<div class="row">

  <div class="span10 columns">
    A <%= @environment.name %> is a type of <%= link_to "web application environment", environments_path %>.
		If you are new to these terms you can read <%= link_to "web application environment", environments_path %>
		to better understand the concepts outlined below.
  </div>

</div>


<%= render :partial => "partials/intro", :object => @environment %>

<h3>Supported Languages</h3>
<ul>
<% @environment.languages.each do |lang| %>  
  <li><%= link_to "#{lang.name} for #{@environment.name}", environment_language_path(lang.slug, @environment.slug) %></li>
<% end %>
</ul>

app/views/home/about.html.erb
<p>
  sqo0l is a place where beginners learn how to build web applications.
</p>

<h3>So You want to learn how to make stuff for the Internet!</h3>

as a programmer you program the functionalities of the application.
What the app <strong>does</strong> is handled by the programer.

a designer is responsible for how the application looks.

a user experience/interface (UX) designer is



<h3>Programming is About Problem Solving.</h3>

Our main goal is to teach you how to solve problems using software.
This is the most important distinction between sqo0l and other tutorial sites.
Once you learn how to solve problems through software, you can build (or learn to build) any application on any platform you want!

Hopjoy helps you become a better problem solver by providing 3 core areas of understanding:

<h3>Understanding Your Environment.</h3>

All concepts and tools we talk about have a basic introduction so that
you understand conceptually <em>how</em> a tool or concept fits into the big picture
and how they relate to one another.

<h3>Understanding Your Tools.</h3>

You should understand <em>why</em> a given project uses the tools and methods outlined in the project
so that when you build your own projects you can answer those questions for yourself and pick the right tool for the job.

<h3>Understanding Your Problem.</h3>

You should build the project by <em>understanding the problems</em>
we are trying to solve and understanding how we've come up with the solutions.
This will allow you to break down your own problems and formulate a solution using tools you choose.

app/views/home/environments.html.erb
<div class="row" >
	<h2 class="main-block highlight"><%= @intro.slug.capitalize %></h2>
</div>

<%= render :partial => "intro", :object => @intro %>

<p>
	Next you should learn about specific types of application environments,
	especially those you want to make applications for.
	<br/>Environments are listed below:
</p>

<ul class="media-grid">
<% @environments.each do |env| %>
  <li>
    <a href="/environments/<%= env.slug %>" style="text-align:center">
      <%= env.slug %>
      <img class="thumbnail" src="http://placehold.it/90x90" alt="">
    </a>
  </li>
<% end %>
</ul>

app/views/home/environments_show.html.erb
<div id="<%= @environment.slug %>" class="row">
  <h2 class="main-block highlight">
    <%= @environment.slug %>
  </h2>
</div>

<div class="row">

  <div class="span10 columns">
    A <%= @environment.slug %> is a type of <%= link_to "web application environment", "/environments" %>.
		If you are new to these terms you can read <%= link_to "web application environments", "/environments" %>
		to better understand the concepts outlined below.
  </div>

</div>


<%= render :partial => "intro", :object => @environment %>

<h3>Supported Languages</h3>
<ul>
<% @environment.languages.each do |lang| %>  
  <li><%= link_to "#{lang.name} for #{@environment.slug}", "/languages/#{lang.name}/#{@environment.slug}" %></li>
<% end %>
</ul>

app/views/home/index.html.erb
<%=raw @intro %>


<div class="row" >

  <div class="span9 columns">
    <h2>Explore Application Environments</h2> 
  </div>
  
</div>

<% @environments.each do |env| %> 
<div class="row">
  <h3 class="main-block">
		<%= link_to env.name, environment_path(env.slug) %>
	</h3>
</div>

<ul> 
<% env.projects.each do |project| %>
  <li>
  <%= link_to project.name, "/projects/#{project.slug}" %>
  </li> 
<% end %>
</ul>

<% end %>


<div class="row" >
  <div class="span9 columns">
    <h2>Explore Careers</h2> 
  </div>
</div>


<div class="row" >
  <div class="span9 columns">
    <h2>Explore Languages</h2> 
  </div>
</div>

<ul> 
<% @languages.each do |lang| %>
  <li>
  <%= link_to lang.name, language_path(lang.slug) %>
  </li> 
<% end %>
</ul>

app/views/home/language_environment.html.erb
<div class="row">
  <h2 class="main-block highlight">
    <%= @language.name.capitalize %> for <%= @environment.slug %>
  </h2>
</div>

<ul>
	<li>What is <%= link_to @language.name, "/languages/#{@language.name}" %>?</li>
	<li>What is <%= link_to @environment.slug, "/environments/#{@environment.slug}" %>?</li>
</ul>

<div class="row">
  <div class="span10 columns">
    <%= raw Page.get("languages/#{@language.name}/#{@environment.slug}") %>
  </div>
</div>

app/views/home/languages.html.erb
<div class="row" >
	<h2 class="main-block highlight"><%= @language.name.capitalize %></h2>
</div>

<%= render :partial => "intro", :object => @language %>

<% # Next Steps %>
<ul>
<% @language.environments.each do |env| %>
  <li>
    <%= link_to "#{@language.name} for #{env.slug}", "/languages/#{@language.name}/#{env.slug}" %>
  </li>
<% end %>  
</ul>

app/views/languages/environment.html.erb
<div class="row">
  <h2 class="main-block highlight">
    <%= @language.name %> for <%= @environment.name %>
  </h2>
</div>

<ul>
	<li>What is <%= link_to @language.name, language_path(@language.slug) %>?</li>
	<li>What is <%= link_to @environment.name, environment_path(@environment.slug) %>?</li>
</ul>

<div class="row">
  <div class="span10 columns">
    <%= raw @language.content(@environment.slug) %>
  </div>
</div>

app/views/languages/show.html.erb
<div class="row" >
	<h2 class="main-block highlight"><%= @language.name %></h2>
</div>

<%= render :partial => "partials/intro", :object => @language %>

<% # Next Steps %>
<ul>
<% @language.environments.each do |env| %>
  <li>
    <%= link_to "#{@language.name} for #{env.name}", environment_language_path(@language.slug, env.slug) %>
  </li>
<% end %>  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hopjoy</title>
  <%= stylesheet_link_tag "bootstrap-1.3.0.min.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <style type="text/css">
  body{
    color:#444;
  }
	body, p {
		line-height:20px;
		font-size: 14px;
	}
  ul li, ol li{
    color:#444;
  }
	.container-fluid {
		
	}

	.container-fluid > .sidebar {
	  width: 300px;
	}
	.container-fluid > .content {
	  margin-left: 320px;
	}
	
	.columns {
		padding-right:20px;
		border-right:1px solid #ccc;
	}
  code {background:transparent;}
  .row {
    margin-bottom:15px;
  }

  #main h2 {
    border-bottom:2px solid #eee;
    margin:15px 0;
  }
    
	h2 {
		margin-left:-40px;
	}
  .main-block {
    background:#eee;
    padding:5px 20px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
  } 

  .highlight {
    background:#57A957;
    color:#FFF;
  }
  .nutshell {
	padding:10px; background:#FBFFDF;
}
  </style>
</head>
<body>
  <div class="container-fluid">
    
    <div class="page-header" style="padding:10px 0">
      <a href="/" class="">hopjoy</a>
      <a href="/about" style="float:right">about</a>
    </div>


		<div class="sidebar" style="height:1px">
			...
		</div>

    <div class="content">
      <%= yield %>
    </div>
    
  </div>


</body>
</html>

app/views/partials/_intro.html.erb
<% if intro.content_exists? :what %>
<div class="row">
  <h3 class="main-block">What is a <%= intro.name %>?</h3>
</div>

<div class="row">
  <div class="span10 columns">
    <%= raw intro.content(:what) %>
  </div>
</div>
<% end %>


<% if intro.content_exists? :example %>
<div class="row">
  <h3 class="main-block">Examples.</h3>
</div>

<div class="row">
  <div class="span10 columns">
    <%= raw intro.content(:example) %>
  </div>
</div>
<% end %>



<% if intro.content_exists? :how %>
<div class="row">
  <h3 class="main-block">How Does a <%= intro.name %> Work?</h3>
</div>

<div class="row">
  <div class="span10 columns">
   	<%= raw intro.content(:how) %>
  </div>
</div>
<% end %>


<% if intro.content_exists? :why %>
<div class="row">
  <h3 class="main-block">Why Should I Care?</h3>
</div>

<div class="row">
  <div class="span10 columns">
  	<%= raw intro.content(:why) %>
  </div>
</div>
<% end %>


<div class="row">
  <h3 class="main-block">Next Steps</h3>
</div>

<div class="row">
  <div class="span10 columns">

  </div>
</div>

app/views/projects/lesson.html.erb
<style type="text/css">
  .columns {
    }
    #main {

    }
    .span3 {
    }
    #main h2 {
      border-bottom:2px solid #eee;
      margin:15px 0;
    }
    #main h4 {
      background:#eee;
      padding-left:5px;
      margin-top:15px;
    }
</style>

<div class="row">
  <div class="span7 columns">
    Lesson Plan
  </div>
  <div class="span9 columns">
    <div id="main">
      <%= raw @project.body_content(:body) %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row" >

  <div class="span9 columns">
    <h2>Project: TicTacToe</h>
  </div>
  <div class="span7 columns" style="text-align:right">
    <h2>level: beginner</h2>
  </div>
</div>

<div class="row">
  <div class="span14 columns offset1" style="padding:10px; background:#eee; height:200px">
    Hello
  </div>
</div>  

<div class="row">
  <h3 class="main-block">Learn About this Environment</h3>
</div>

<div class="row">
  <div class="span5 columns">
    &#160;
  </div>
  <div class="span10 columns">
    <div >
      
      <ul>
        <li><%= link_to @environment.name, "/environments/#{@environment.slug}"  %></li>
      </ul>  

    </div>
  </div>
</div>

<div class="row">
  <h3 class="main-block">Learn About the Tools</h3>
</div>

<div class="row">

  <div class="span5 columns">
    &#160;
  </div>
  
  <div class="span10 columns">
    <h4>Languages Used</h4>
    <ul>
    <% @project.languages.each do |lang| %>
      <li><%= link_to "#{lang.name} for #{@environment.name}", "/languages/#{lang.slug}/#{@environment.slug}" %></li>
    <% end %>
    </ul>  

    <h4>Frameworks Used</h4>
    <ul>
      <li>Jquery</li>
    </ul>
  </div>

</div>

  


<div class="row">
  <h3 class="main-block">Setup Your Development Environment</h3>
</div>

<div class="row">

  <div class="span5 columns">
    &#160;
  </div>
  
  <div class="span10 columns">
    <ul>
      <li>Core Programming Environment</li>
      <li>Browser-based development</li>
      <li>Language-based development</li>
    </ul>
  </div>

</div>


<div class="row">
  <h3 class="main-block">Project Steps</h3>
</div>

<div class="row">
  
  <div class="span5 columns">
    &#160;
  </div>
  
  <div class="span10 columns">
    <%= raw @project.content %>
  </div>
  
</div>